services:
  db:
    container_name: db
    hostname: db
    restart: unless-stopped
    image: mariadb:10.7.3-focal
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/log:/var/log/mysql
      - ./db/migrations:/docker-entrypoint-initdb.d
    environment:
        TZ: 'Asia/Tokyo'
        MYSQL_ROOT_PASSWORD: 'root'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin